---
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present


- name: Configuring docker-ce repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644


- name: Install docker
  yum:
    name: '{{ item }}'
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io


- name: Starting and Enabling Docker service
  systemd:
    name: docker
    state: started
    enabled: yes


- name: Install epel-release
  yum:
    name: epel-release
    state: present


- name: Install python-pip
  dnf:
    name: '{{ item }}'
    state: present
  loop: 
    - python3
    # - python-devel
    - gcc


- name: Update python-pip
  pip:
   name: pip
   extra_args: --upgrade


- name: Install docker-compose
  pip:
    name: docker-compose  
    

