---
- name: Copy docker compose file
  become_user: vagrant
  copy:
    src: docker-compose.yml
    dest: /home/vagrant/docker-compose.yml

- name: Copy files
  become_user: vagrant
  copy:
    src: .
    dest: /home/vagrant/

# - name: Enable run docker another user
#   shell: groupadd docker
#   ignore_errors: true

- name: Enable run docker another user
  shell:  usermod -aG docker vagrant
  ignore_errors: true


- name: Enable run docker another user
  shell: sudo chmod 666 /var/run/docker.sock
  ignore_errors: true



- name: Run docker-compose
  become_user: vagrant
  shell: docker-compose -f /home/vagrant/docker-compose.yml up -d