---
version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 81:81
      - 82:82
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/php.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/js.conf:/etc/nginx/conf.d/js.conf:ro
      - ./nginx/python.conf:/etc/nginx/conf.d/python.conf:ro
      - ./php:/var/www/html:rw
    depends_on:
      - fpm
      - nodeserver
      - flask_app
    networks:
      - web

  fpm:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html:rw
    ports:
      - "9000:9000"
    networks:
      - web

  nodeserver:
    build: ./js
    ports:
      - "5000:5000"
    networks:
      - web

  flask_app:
    container_name: flask_app
    restart: always
    build: ./python
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
    networks:
      - web

networks:
  web: